<a href="https://colab.research.google.com/github/7ZXU/AI/blob/main/MachineLearningChallenge/ML_Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 도전학기 '빅데이터와 인공지능을 활용한 시스템 강건설계' 머신러닝 챌런지!

#### - 머신러닝 챌런지 목표 
: 실습내용을 바탕으로 직접 인공지능 모델을 학습시키고 새로운 검사 데이터에 대해 진단결과를 출력할 수 있도록 코드를 작성하는 능력 평가


#### - 데이터 출처 (데이터 챌런지 2단계의 Fault1 & 2 인덱싱 데이터 중 일부 발췌) 
: 2015 PHM Conference Data Callenge (https://www.phmsociety.org/events/conference/phm/15/data-challenge)

. 

. 

.


## 머신러닝 챌런지 수행 단계 가이드


#### (1) 주어진 데이터를 사용해 직접 특징 추출/선택 및 머신러닝을 수행 (학습 과정에서 작성한 코드는 제출할 필요 없음.)
- 학습용 데이터 : TrainingData 폴더 내 "Fault1_Train1 ~ 50" 및 "Fault2_Train1 ~ 50" 등 총 100개 파일
- 머신러닝을 위한 학습데이터 레이블(Label)은 직접 만들어 사용


- 어떤 특징을 사용 및 선택할지, 어떤 머신러닝 알고리즘을 어떻게 사용할지 등 모든 과정 각자 자유롭게 결정


- [필수] 학습완료된 머신러닝 모델은 제공된 폴더(MLmodel) 안에 저장! (모델의 파일이름은 양식 따로 없음)

#### (2) 학습완료 후 현재 코드파일에서 "저장된 머신러닝 모델 파일" 및 "검사 데이터+레이블" 불러와서 진단 결과 출력하도록 코드 작성
- 검사용 데이터 : TestData 폴더 내 "TestData1 ~ 20" 등 총 20개 파일 + 레이블(Label) 2개 파일
- 검사데이터 불러오는 코드 수정x (채점 시 동일한 경로 및 동일한 이름의 데이터파일 사용 예정)


- 학습된 머신러닝 모델 파일의 경로(MLmodel 폴더) 및 파일 이름에 맞게 코드 작성하여 모델 불러오기

#### (3) 최종 저장된 현재 코드파일(.ipynb) 및 머신러닝 모델 들어있는 폴더(MLmodel) 함께 1개 압축파일(.zip)로 만들어 제출
- 압축파일 이름 ST(수강생 번호)_ML (예시 : 'ST000_ML.zip'  //  'ST00_ML.zip'  //  'ST0_ML.zip')
- 코드 마지막 저장 시 주피터노트북 상단 메뉴 'Kernel > Restart & Clear Output > Restart and Clear All Output' 수행 후 저장하고 제출

.

.

.

### 필요한 라이브러리 import
- numpy, pandas 등 필요한 라이브러리들 불러오기

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as sp
import seaborn           as sb
import scipy.stats       as sp
import pickle
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm,metrics
import joblib

### 학습완료된 머신러닝 모델 불러오기
- 직접 학습하여 저장한 머신러닝 모델 (제공된 MLmodel 폴더안에 저장된) 파일 불러오기

In [ ]:
KNN_model = joblib.load('/content/drive/MyDrive/colab/BDnML/ML_ChallengeMaterials/MLmodel/KNN_model.plk')
SVM_model = joblib.load('/content/drive/MyDrive/colab/BDnML/ML_ChallengeMaterials/MLmodel/SVM_model.plk')

/usr/local/lib/python3.6/dist-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator KNeighborsClassifier from version 0.23.1 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator SVC from version 0.23.1 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

### 검사 데이터 및 레이블 불러오기 (코드 수정x)
* TestData1  ~  10 : Fault1 데이터 (Label: 0 혹은 [1,0])
* TestData11 ~ 20 : Fault2 데이터  (Label: 1 혹은 [0,1])


* 제공된 검사 데이터(TestData1~20)와 실제 채점용 검사 테스트 데이터는 파일 이름만 동일한 "다른 데이터"를 사용할 예정 (Fault1, 2 순서  또한 랜덤)

In [ ]:
for i in range(1,21): #1이상 21미만
    s = "TestData%d = pd.read_csv('/content/drive/MyDrive/colab/BDnML/ML_ChallengeMaterials/TestData/TestData%d', header=None)"%(i,i)
    exec(s) #문자열s 동적 실행 
    
TestData_Label        = np.array(pd.read_csv('/content/drive/MyDrive/colab/BDnML/ML_ChallengeMaterials/TestData/TestData_Label', header=None))
TestData_Label_forANN = np.array(pd.read_csv('/content/drive/MyDrive/colab/BDnML/ML_ChallengeMaterials/TestData/TestData_Label_forANN', header=None))

TestData20 #TestData임의 출력

       0    1   2    3
0    720  588   5  626
1    727  675   5  571
2    720  588   5  626
3    727  675   5  571
4    730  455  69  708
..   ...  ...  ..  ...
223  774  493  69  685
224  761  478  69  694
225  757  473  69  697
226  754  468  69  700
227  747  466  69  702

[228 rows x 4 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### 데이터 특징 추출
* 학습에 사용된 데이터 특징과 동일하게 추출 (순서도 동일)

In [ ]:
NoOfData    = 10  # Fault1, Fault2 각 10개씩 
NoOfSensor  = 4   # 가속도(Acceleration), 전압(Voltage), 전류(Current), 
NoOfFeature = 10   # 특징 개수:10개 (순서: Max, Min, Mean, RMS, Variance, Skewness, Kurtosis, Crest factor, Impulse factor, Shape factor)
def rms(x): # RMS 함수 정의
    return np.sqrt(np.mean(x**2)) #제곱평균제곱근

In [ ]:
FeatureData_Fault1   = np.zeros((NoOfSensor*NoOfFeature , NoOfData))
FeatureData_Fault2   = np.zeros((NoOfSensor*NoOfFeature , NoOfData))
#np.zeros 0으로된 행렬 반환
#np.zeors(행, 열) = (40,10)

for i in range(NoOfData) : 
    s1 = 'temp_data1 = TestData%d'%(i+1) #range() : 0부터 시작 #1~10
    s2 = 'temp_data2 = TestData%d'%(i+11) #11~20
    exec(s1)
    exec(s2)
    
    # Time Domain 특징값 추출
    for j in range(NoOfSensor):
        
        # Fault1 Time Domain Feature
        FeatureData_Fault1[10*j+0, i] = np.max(temp_data1.iloc[:,j])
        FeatureData_Fault1[10*j+1, i] = np.min(temp_data1.iloc[:,j])
        FeatureData_Fault1[10*j+2, i] = np.mean(temp_data1.iloc[:,j])
        FeatureData_Fault1[10*j+3, i] = rms(temp_data1.iloc[:,j])
        FeatureData_Fault1[10*j+4, i] = np.var(temp_data1.iloc[:,j])
        FeatureData_Fault1[10*j+5, i] = sp.skew(temp_data1.iloc[:,j])
        FeatureData_Fault1[10*j+6, i] = sp.kurtosis(temp_data1.iloc[:,j])
        FeatureData_Fault1[10*j+7, i] = np.max(temp_data1.iloc[:,j])/rms(temp_data1.iloc[:,j])
        FeatureData_Fault1[10*j+8, i] = rms(temp_data1.iloc[:,j])/np.mean(temp_data1.iloc[:,j])
        FeatureData_Fault1[10*j+9, i] = np.max(temp_data1.iloc[:,j])/np.mean(temp_data1.iloc[:,j])
        
        # Fault2 Time Domain Feature
        FeatureData_Fault2[10*j+0, i] = np.max(temp_data2.iloc[:,j])
        FeatureData_Fault2[10*j+1, i] = np.min(temp_data2.iloc[:,j])
        FeatureData_Fault2[10*j+2, i] = np.mean(temp_data2.iloc[:,j])
        FeatureData_Fault2[10*j+3, i] = rms(temp_data2.iloc[:,j])
        FeatureData_Fault2[10*j+4, i] = np.var(temp_data2.iloc[:,j])
        FeatureData_Fault2[10*j+5, i] = sp.skew(temp_data2.iloc[:,j])
        FeatureData_Fault2[10*j+6, i] = sp.kurtosis(temp_data2.iloc[:,j])
        FeatureData_Fault2[10*j+7, i] = np.max(temp_data2.iloc[:,j])/rms(temp_data2.iloc[:,j])
        FeatureData_Fault2[10*j+8, i] = rms(temp_data2.iloc[:,j])/np.mean(temp_data2.iloc[:,j])
        FeatureData_Fault2[10*j+9, i] = np.max(temp_data2.iloc[:,j])/np.mean(temp_data2.iloc[:,j])
        
print(FeatureData_Fault1.shape)
print(FeatureData_Fault2.shape)

(40, 10)
(40, 10)

### 데이터 특징 선택
* 주의 : 검사 데이터로 별도의 t-Test를 수행(P-value 계산)하지 말 것 >> 학습 과정에서 선택된 특징과 동일한 특징 선택 및 동일한 순서로 배열

In [ ]:
FeatureSelected_Trained = pd.DataFrame(np.concatenate([FeatureData_Fault1,FeatureData_Fault2],axis=1)) #열 기준으로 이어 붙여라 (40, 20)
FeatureData_Fault1_df = pd.DataFrame(FeatureData_Fault1)
FeatureData_Fault2_df = pd.DataFrame(FeatureData_Fault2)

In [ ]:
P_value_Rank = pd.read_csv('/content/drive/MyDrive/colab/BDnML/ML_ChallengeMaterials/MLmodel/P_value_Rank',header = None)
P_value_Rank
#p_value 낮은 순서로 배열 (1열 P_value)

       0         1
0   24.0  0.000044
1   22.0  0.000214
2   30.0  0.000388
3   11.0  0.000491
4    6.0  0.000632
5   25.0  0.001465
6   23.0  0.001550
7    1.0  0.002120
8   28.0  0.002691
9   31.0  0.005749
10  10.0  0.006931
11   2.0  0.008744
12   3.0  0.009943
13  27.0  0.010508
14  17.0  0.016478
15  19.0  0.018048
16   7.0  0.020602
17  29.0  0.020714
18   9.0  0.022516
19  37.0  0.028903
20  39.0  0.033841
21  21.0  0.037867
22  36.0  0.039055
23  26.0  0.049032
24  35.0  0.074013
25  15.0  0.105442
26  16.0  0.162347
27   5.0  0.393722
28  14.0  0.645772
29  34.0  0.653691
30  20.0  0.660608
31  18.0  0.667222
32   8.0  0.816135
33  33.0  0.935636
34  32.0  0.942829
35   0.0  0.943292
36  12.0  0.949095
37   4.0  0.953318
38  38.0  0.964511
39  13.0  0.975305

In [ ]:
Rank = 5
NoOfData = 10

Fault1   = np.zeros((Rank,NoOfData))
Fault2   = np.zeros((Rank,NoOfData))

for i in range(Rank):
    #FeatureData_Fault (40,10)
    index         = int(P_value_Rank.iloc[i,0])                      # P-Value의 [0]열은 해당 통계적 특징의 행 위치를 뜻한다.
    Fault1[i,:]   = FeatureData_Fault1_df.iloc[index,:].values          # Normal각 행에 index 째의 데이터 저장(P value가 가장 낮은 순으로)
    Fault2[i,:] = FeatureData_Fault2_df.iloc[index,:].values    #(5, 10)

# 정상, 고장 특징값 합치기    
FeatureSelected = pd.DataFrame(np.transpose(np.concatenate([Fault1, Fault2] , axis=1))) #(5, 20)
#np.tranpose : 행과 열 바꾸기 #(20,5)

print("Selected Feature Data Size :", FeatureSelected.shape)
FeatureSelected

Selected Feature Data Size : (20, 5)

              0          1      2      3         4
0    653.315244  56.299238  726.0  424.0  2.322018
1    679.001309  84.472822  714.0  444.0  1.863040
2   1015.277954  27.941171  798.0  293.0  0.364123
3    364.459733  85.461141  730.0  417.0 -1.125279
4    679.001309  84.472822  714.0  444.0  1.863040
5    777.098610  53.665403  843.0  198.0  2.888742
6    653.315244  56.299238  726.0  424.0  2.322018
7    887.187600  50.784394  770.0  345.0  0.210322
8   1031.561982  23.711396  728.0  421.0  8.735430
9    994.248329  44.093940  747.0  387.0  3.112891
10   336.473015  63.220736  711.0  450.0 -0.392568
11   765.843222  57.636816  709.0  453.0  2.820731
12   729.481456  54.832887  746.0  388.0 -1.174188
13   306.947554  88.623762  710.0  451.0  5.820566
14   765.843222  57.636816  709.0  453.0  2.820731
15   365.759605  62.703734  803.0  284.0 -0.161406
16   336.473015  63.220736  711.0  450.0 -0.392568
17     0.245836  68.564528  650.0  550.0 -0.183168
18     0.246914  68.444444  671.0  516.0 -0.920315
19   378.052324  62.649123  738.0  403.0  0.370068

In [ ]:
TestData_Label = pd.read_csv('/content/drive/MyDrive/colab/BDnML/ML_ChallengeMaterials/TestData/TestData_Label',header = None)
TestData_Label

    0
0   0
1   0
2   0
3   0
4   0
5   0
6   0
7   0
8   0
9   0
10  1
11  1
12  1
13  1
14  1
15  1
16  1
17  1
18  1
19  1

### 검사 데이터의 진단 결과 출력 및 정확도 평가
- 상기 불러온 검사 데이터 20개의 특징(선택된)데이터 및 레이블을 이용하여 머신러닝 모델의 정확도 평가
- 정확도 60% 미만일 경우 감점. 80% 이상일 경우 가산점 (채점용 검사 데이터로 정확도 평가 결과 기준)

In [ ]:
knnscore = KNN_model.score(FeatureSelected , TestData_Label)
print('Accuracy: {:.2f}%'.format(knnscore*100))

Accuracy: 95.00%

In [ ]:
SVM_model_Final = joblib.load('/content/drive/MyDrive/colab/BDnML/ML_ChallengeMaterials/MLmodel/SVM_model.plk')
Predicted = np.array(SVM_model.predict(FeatureSelected))
svmscore = metrics.accuracy_score(TestData_Label , Predicted)
print('Accuracy: {:.2f}%'.format(svmscore*100))

/usr/local/lib/python3.6/dist-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator SVC from version 0.23.1 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

AttributeError: ignored